### ISSUE TITLE
PG sync to MySQL: Error in the 'from' worker: ERROR: relation "table1" does not exist

### ISSUE THREAD

**Issue by tomSDL** [willbryant/kitchen_sync#62] opened 2019-05-09 07:17 UTC
Hi Will,

I am getting the following error:-

ks --from postgresql://logsreader_single:password@192.168.99.1/database_single  --to mysql://username:password@localhost/3CX --debug

Error in the 'from' worker: ERROR:  relation "table1" does not exist

SELECT tablename FROM pg_tables WHERE schemaname = ANY (current_schemas(false)) ORDER BY pg_relation_size(tablename::text) DESC, tablename ASC
Connection closed
Kitchen Syncing failed.

**Comment by willbryant** [comment] 2019-05-09 09:42
Huh.  Seems weird that it gives this error while running `SELECT tablename FROM pg_tables WHERE schemaname = ANY (current_schemas(false)) ORDER BY pg_relation_size(tablename::text) DESC, tablename ASC` which doesn't actually mention `table1`.

Do you have a table called `table1` at the source end?  Are you using multiple schemas in the postgresql database?

**Comment by willbryant** [comment] 2019-05-09 12:22
Please retest with v1.16 which rewrote that query in order to fix #61.

**Comment by tomSDL** [comment] 2019-05-17 19:44
Hi,

I cant build 1.16.1 - I am not getting another error on 1.16 though that I have posted in another thread.

`
/src/substitute_primary_key.h:22:77: error: ‘none_of’ was not declared in this scope
   if (key.unique && none_of(key.columns.begin(), key.columns.end(), nullable)) {
                                                                             ^
CMakeFiles/ks_mysql.dir/build.make:62: recipe for target 'CMakeFiles/ks_mysql.dir/src/ks_mysql.cpp.o' failed
make[2]: *** [CMakeFiles/ks_mysql.dir/src/ks_mysql.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/ks_mysql.dir/all' failed
make[1]: *** [CMakeFiles/ks_mysql.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2


`

**Comment by willbryant** [comment] 2019-05-18 02:10
What OS/version are you using?

**Comment by willbryant** [comment] 2019-05-18 02:38
Also, I don't think that you were compiling v1.16.1.  The function `none_of` is not used in v1.16.1 - it's in a commit in master that hasn't been released yet.

Did you accidentally checkout origin/master instead?

**Comment by willbryant** [comment] 2019-06-25 08:42
I still can't reproduce this.  Need more info as above, please try with v1.16.1 or v1.17 (not master).

**Comment by willbryant** [comment] 2019-08-12 02:21
No feedback, closing.

**Closed by willbryant** 2019-08-12 02:21 UTC
Labels: incomplete
